# Site settings
author: Antoniette
title: AntCodex
header-img: img/home-bg.png
email: antvickio@gmail.com
copyright_name: Antoniette
description: > # this means to ignore newlines until "baseurl:"
  What it takes Ant to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  antvickio

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
